# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/cat.proto", :syntax => :proto3) do
    add_message "GetMyCatMessage" do
      optional :target_cat, :string, 1
    end
    add_message "MyCatResponse" do
      optional :name, :string, 1
      optional :kind, :string, 2
    end
  end
end

GetMyCatMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMyCatMessage").msgclass
MyCatResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MyCatResponse").msgclass
