# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/cat.proto for package ''

require 'grpc'
require 'proto/cat_pb'

module Cat
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Cat'

    rpc :GetMyCat, GetMyCatMessage, MyCatResponse
  end

  Stub = Service.rpc_stub_class
end
